# Generated by Django 2.2.3 on 2019-07-07 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0002_auto_20190707_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('yeaar', models.IntegerField()),
                ('fee_type', models.CharField(choices=[('Academic', 'Academic'), ('Hostel', 'Hostel'), ('Academic and Hostel', 'Academic and Hostel')], max_length=32)),
                ('payment_type', models.CharField(max_length=16)),
                ('challan_no', models.CharField(max_length=16)),
                ('total_fee', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('fee_transfer_id', models.CharField(max_length=32)),
                ('transfer_date', models.DateField()),
                ('fee_verified', models.NullBooleanField()),
                ('account_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Branch')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
