# Generated by Django 2.2.3 on 2019-07-08 17:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roll_no', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('details', django.contrib.postgres.fields.jsonb.JSONField()),
                ('is_verified', models.CharField(choices=[('0', 'pending'), ('1', 'accept'), ('2', 'deny')], max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='fee',
            name='fee_verified',
        ),
    ]
