# Generated by Django 2.2.3 on 2019-07-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_auto_20190708_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fee',
            old_name='yeaar',
            new_name='year',
        ),
        migrations.AlterField(
            model_name='feeregister',
            name='is_verified',
            field=models.CharField(choices=[(0, 'pending'), (1, 'accept'), (2, 'deny')], default=1, max_length=16),
        ),
    ]
