# Generated by Django 2.2.3 on 2019-07-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_auto_20190708_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='fee',
            name='mode_of_payment',
            field=models.CharField(choices=[('RTGS', 'RTGS'), ('NIFT', 'NIFT'), ('ONLINE', 'ONLINE'), ('CHALLAN', 'CHALLAN')], default=1, max_length=16),
            preserve_default=False,
        ),
    ]
