# Generated by Django 2.2.3 on 2019-07-22 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_auto_20190718_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='challan_no',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
