# Generated by Django 2.2.3 on 2019-07-22 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0005_auto_20190722_0322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fee',
            old_name='fee_transfer_id',
            new_name='transfer_id',
        ),
    ]
