# Generated by Django 2.2.3 on 2019-07-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0006_auto_20190722_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeregister',
            name='is_verified',
            field=models.CharField(choices=[(0, 'pending'), (1, 'accept'), (2, 'deny')], default=0, max_length=16),
        ),
    ]
