# Generated by Django 2.2.3 on 2019-07-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0007_auto_20190722_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeregister',
            name='form_id',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='feeregister',
            name='session',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
