# Generated by Django 2.2.3 on 2019-07-27 21:55

from django.db import migrations, models
from datetime import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0009_auto_20190722_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeregister',
            name='transfer_date',
            field=models.DateField(default=datetime.now()),
            preserve_default=False,
        ),
    ]
