# Generated by Django 2.2.3 on 2019-07-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0010_feeregister_transfer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='mode_of_payment',
            field=models.CharField(choices=[('RTGS', 'RTGS'), ('NIFT', 'NIFT'), ('ONLINE', 'ONLINE'), ('CHALLAN', 'CHALLAN'), ('CASH', 'CASH')], max_length=16),
        ),
    ]
