# Generated by Django 2.2.3 on 2019-07-16 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semesters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='year',
            new_name='semester',
        ),
    ]
