# Generated by Django 2.2.3 on 2019-07-07 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('hod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roll_no', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('father_name', models.CharField(max_length=64)),
                ('mother_name', models.CharField(max_length=64)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNSPECIFIED', 'Unspecified')], max_length=16)),
                ('category', models.CharField(choices=[('GEN', 'Gen'), ('OBC', 'OBC'), ('ST', 'ST'), ('SC', 'SC')], max_length=16)),
                ('sub_category', models.CharField(max_length=16)),
                ('address', models.TextField()),
                ('mobile_no', models.CharField(max_length=10)),
                ('father_mobile_no', models.CharField(max_length=10)),
                ('mother_mobile_no', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('addhar_no', models.CharField(max_length=16, unique=True)),
                ('mode_of_admission', models.CharField(choices=[('vacant_seat', 'Vacant Seat'), ('upsee', 'UPSEE')], max_length=16)),
                ('mode_of_admission_category', models.CharField(choices=[('Lateral_entry', 'Lateral Entry'), ('FW', 'FW'), ('EWS', 'EWS'), ('other', 'other')], max_length=16)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Branch')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
