# Generated by Django 2.2.3 on 2019-07-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20190707_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic',
            name='academic_type',
            field=models.CharField(choices=[('HighSchool', 'High School'), ('Intermediate', 'Intermediate'), ('UgOrDiploma', 'Ug or Diploma')], max_length=16),
        ),
    ]
