# Generated by Django 2.2.3 on 2019-07-22 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sub_category',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
