# Generated by Django 2.2.3 on 2019-07-23 20:50

from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20190722_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='upload',
            field=models.ImageField(upload_to=students.models.upload_location),
        ),
    ]
