# Generated by Django 2.2.3 on 2019-07-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20190728_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobile_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_mobile_no',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
