# Generated by Django 2.2.3 on 2019-07-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20190728_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mode_of_admission_category',
            field=models.CharField(choices=[('Lateral_entry', 'Lateral Entry'), ('FW', 'FW'), ('EWS', 'EWS'), ('Open', 'Open')], max_length=16),
        ),
    ]
